<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Beban extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Beban_model');
        $this->load->library('form_validation');
    }    
function data() {
        $table = 'beban';
        $primaryKey = 'id';
        $columns = array(
         array('db' => 'id', 'dt' => 0),array('db' => 'id', 'dt' => 0),
array('db' => 'beban', 'dt' => 1),
array(
                'db' => 'id',
                'dt' => 2,
                'formatter' => function( $d, $row ) {
            return 
            // anchor('Beban/read/'.$d,'<i class="fa fa-eye"></i>',"class='btn btn-sm btn-danger'").' '.
                   anchor('Beban/update/'.$d,'<i class="fa fa-edit"></i>',"class='btn btn-sm btn-danger'");
                   // .' '.
                   // anchor('Beban/delete/'.$d,'<i class="fa fa-trash"></i>',"class='btn btn-sm btn-danger'");
                }
            )
        );

        $sql_details = array(
            'user' => $this->db->username,
            'pass' => $this->db->password,
            'db' => $this->db->database,
            'host' => $this->db->hostname
        );
        
        $this->load->library('ssp');
        echo json_encode(
                SSP::simple($_GET, $sql_details, $table, $primaryKey, $columns)
        );
    }

    public function index()
    {
        $beban = $this->Beban_model->get_all();

        $data = array(
            'beban_data' => $beban
        );

        $this->template->load('template','beban/beban_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Beban_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'beban' => $row->beban,
	    );
            $this->load->view('beban/beban_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('beban'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('beban/create_action'),
	    'id' => set_value('id'),
	    'beban' => set_value('beban'),
	);
        $this->template->load('template','beban/beban_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'beban' => $this->input->post('beban',TRUE),
	    );

            $this->Beban_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('beban'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Beban_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('beban/update_action'),
		'id' => set_value('id', $row->id),
		'beban' => set_value('beban',$row->beban),
	    );
            $this->template->load('template','beban/beban_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('beban'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'beban' => $this->input->post('beban',TRUE),
	    );

            $this->Beban_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('beban'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Beban_model->get_by_id($id);

        if ($row) {
            $this->Beban_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('beban'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('beban'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('beban', 'beban', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Beban.php */
/* Location: ./application/controllers/Beban.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-03-01 07:14:12 */
/* http://harviacode.com */