<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Size extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Size_model');
        $this->load->library('form_validation');
    }    
function data() {
        $table = 'size';
        $primaryKey = 'id';
        $columns = array(
         array('db' => 'id', 'dt' => 0),array('db' => 'id', 'dt' => 0),
array('db' => 'size', 'dt' => 1),
array('db' => 'kode', 'dt' => 2),
array(
                'db' => 'id',
                'dt' => 3,
                'formatter' => function( $d, $row ) {
            return 
            // anchor('Size/read/'.$d,'<i class="fa fa-eye"></i>',"class='btn btn-sm btn-danger'").' '.
                   anchor('Size/update/'.$d,'<i class="fa fa-edit"></i>',"class='btn btn-sm btn-danger'");
                   // .' '.
                   // anchor('Size/delete/'.$d,'<i class="fa fa-trash"></i>',"class='btn btn-sm btn-danger'");
                }
            )
        );

        $sql_details = array(
            'user' => $this->db->username,
            'pass' => $this->db->password,
            'db' => $this->db->database,
            'host' => $this->db->hostname
        );
        
        $this->load->library('ssp');
        echo json_encode(
                SSP::simple($_GET, $sql_details, $table, $primaryKey, $columns)
        );
    }

    public function index()
    {
        $size = $this->Size_model->get_all();

        $data = array(
            'size_data' => $size
        );

        $this->template->load('template','size/size_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Size_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'size' => $row->size,
		'kode' => $row->kode,
	    );
            $this->load->view('size/size_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('size'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('size/create_action'),
	    'id' => set_value('id'),
	    'size' => set_value('size'),
	    'kode' => set_value('kode'),
	);
        $this->template->load('template','size/size_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'size' => $this->input->post('size',TRUE),
		'kode' => $this->input->post('kode',TRUE),
	    );

            $this->Size_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('size'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Size_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('size/update_action'),
		'id' => set_value('id', $row->id),
		'size' => set_value('size', $row->size),
		'kode' => set_value('kode', $row->kode),
	    );
            $this->template->load('template','size/size_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('size'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'size' => $this->input->post('size',TRUE),
		'kode' => $this->input->post('kode',TRUE),
	    );

            $this->Size_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('size'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Size_model->get_by_id($id);

        if ($row) {
            $this->Size_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('size'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('size'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('size', 'size', 'trim|required|is_unique[size.size]');
	$this->form_validation->set_rules('kode', 'kode', 'trim|required|is_unique[size.kode]');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Size.php */
/* Location: ./application/controllers/Size.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-02-27 12:33:24 */
/* http://harviacode.com */