<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Barangg_model extends CI_Model
{

    public $table = 'barang';
    public $view = 'view_baranggg';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $data = $this->db->get('barang')->result_array();
        return $data;

        // $this->db->order_by($this->id, $this->order);
        // return $this->db->get($this->table)->result();
    }

   //Ambil data satu barang
    public function get_one($where){
        $this->db->where($where);
        return $this->db->get('barang')->row_array();
    }

    //Tambah data barang
    public function add($data){

            //Tambahkan data
            $this->db->insert('barang', $data);

            //Ambil data id barang
            $idbarang = $this->db->insert_id();

            return $idbarang;
    }

    //Edit data barang
    public function edit($where, $data){
        $this->db->where($where);
        return $this->db->update('barang', $data);
    }

    //Hapus data barang
    public function delete($where){
        $this->db->where($where);
        return $this->db->delete('barang');
    }
}

/* End of file Barang_model.php */
/* Location: ./application/models/Barang_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-06 14:38:35 */
/* http://harviacode.com */