<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pembelian_model extends CI_Model
{

    public $table = 'pembelian';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }


    function delete_pembelian($id)
    {
        $this->db->where('idPembelian', $id);
        $this->db->delete('detailpembelian');
    }

        function get_by_id_pembelian($id)
    {
        $this->db->where('idPembelian', $id);
        return $this->db->get('detailpembelian')->row();
    }
    
    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
   
    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pembelian_model.php */
/* Location: ./application/models/Pembelian_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-10 21:46:34 */
/* http://harviacode.com */