<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pemesan_model extends CI_Model
{

    public $table = 'pemesan';
    public $id = 'id';
    public $idpemesan = 'idpemesan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
      function get_by_idd($id)
    {
        $this->db->where('idPemesan', $id);
        return $this->db->get('detailpesanan')->row();
    }

    // function get_by_idpemesan($idpemesan)
    // {
    //     $this->db->where($this->id, $idpemesan);
    //     return $this->db->get('detailpesanan')->row();
    // }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('tanggal_pesan', $q);
	$this->db->or_like('tanggal_diambil', $q);
	$this->db->or_like('idPelanggan', $q);
	$this->db->or_like('idAdmin', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('tanggal_pesan', $q);
	$this->db->or_like('tanggal_diambil', $q);
	$this->db->or_like('idPelanggan', $q);
	$this->db->or_like('idAdmin', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    function insert_temp($data)
    {
        $this->db->insert('detailpesanan_temp',$data);
        # code...
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }


   function delete_pemesan($id)
    {
        $this->db->where('idPemesan', $id);
        $this->db->delete('detailpesanan');
    }

}

/* End of file Pemesan_model.php */
/* Location: ./application/models/Pemesan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-07 12:53:49 */
/* http://harviacode.com */